version: "3"

services:
  backend:
    build: ./server
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/lostfound

  mongo:
    image: mongo
    ports:
      - "27017:27017"