version: "3.8"

services:

  backend:
    build:
      context: .              # ✅ build from root (important)
      dockerfile: server/Dockerfile
    container_name: lostfound-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/lostfound
    volumes:
      - .:/app               # ✅ optional (for live updates)

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: